// --- Shared skill icon catalog ----------------------------------------------
// Single source of truth for mapping a skill *name* to a brand icon + accent
// color. Consumed by both the public Home page (to render skill chips) and the
// admin Skills page (to preview icons and power the "add from catalog" picker).
//
// Icons are derived from the skill name at render time — no icon is stored in
// the database. Every skill offered by the admin catalog picker uses a canonical
// name that exists in SKILL_ICONS below, so its icon always resolves.

import {
    Shield,
    ShieldCheck,
    Database,
    GitBranch,
    GitMerge,
    Sparkles,
    Plug,
    Server,
    Code2,
    CreditCard,
    TestTube,
    Users,
    Workflow,
    RefreshCw,
    BarChart3,
    Cloud,
    Brain,
    MessageSquare,
    Search,
    Smartphone,
    Layers,
    Boxes,
    Network,
    Lock,
    Terminal,
    Palette,
    Globe,
    KanbanSquare,
    Binary,
    Component,
    Waypoints,
    Bug,
    Gauge,
} from 'lucide-react';
import {
    SiPython,
    SiPhp,
    SiJavascript,
    SiTypescript,
    SiCplusplus,
    SiC,
    SiSharp,
    SiGo,
    SiRust,
    SiRuby,
    SiKotlin,
    SiSwift,
    SiDart,
    SiScala,
    SiR,
    SiPerl,
    SiLua,
    SiHaskell,
    SiElixir,
    SiGnubash,
    SiSolidity,
    SiOpenjdk,
    SiCoffeescript,
    SiHtml5,
    SiCss,
    SiReact,
    SiVuedotjs,
    SiAngular,
    SiNextdotjs,
    SiNuxt,
    SiSvelte,
    SiNodedotjs,
    SiExpress,
    SiNestjs,
    SiLaravel,
    SiInertia,
    SiDjango,
    SiFlask,
    SiFastapi,
    SiSpring,
    SiSpringboot,
    SiRubyonrails,
    SiSymfony,
    SiDotnet,
    SiJquery,
    SiBootstrap,
    SiTailwindcss,
    SiMui,
    SiChakraui,
    SiAntdesign,
    SiRadixui,
    SiShadcnui,
    SiRedux,
    SiVite,
    SiWebpack,
    SiSass,
    SiGraphql,
    SiApollographql,
    SiFlutter,
    SiElectron,
    SiThreedotjs,
    SiAstro,
    SiRemix,
    SiSolid,
    SiGatsby,
    SiAlpinedotjs,
    SiPandas,
    SiNumpy,
    SiScipy,
    SiScikitlearn,
    SiTensorflow,
    SiPytorch,
    SiKeras,
    SiOpencv,
    SiPlotly,
    SiStreamlit,
    SiJupyter,
    SiHuggingface,
    SiLangchain,
    SiGit,
    SiGithub,
    SiGitlab,
    SiBitbucket,
    SiDocker,
    SiKubernetes,
    SiMysql,
    SiPostgresql,
    SiMongodb,
    SiRedis,
    SiSqlite,
    SiMariadb,
    SiFirebase,
    SiSupabase,
    SiGooglecloud,
    SiVercel,
    SiNetlify,
    SiDigitalocean,
    SiCloudflare,
    SiNginx,
    SiApache,
    SiLinux,
    SiUbuntu,
    SiDebian,
    SiRedhat,
    SiFigma,
    SiSketch,
    SiPostman,
    SiInsomnia,
    SiSwagger,
    SiJira,
    SiConfluence,
    SiTrello,
    SiNotion,
    SiAsana,
    SiClickup,
    SiVim,
    SiAndroidstudio,
    SiXcode,
    SiIntellijidea,
    SiTerraform,
    SiAnsible,
    SiJenkins,
    SiGithubactions,
    SiCircleci,
    SiPrisma,
    SiElasticsearch,
    SiApachekafka,
    SiRabbitmq,
    SiGrafana,
    SiPrometheus,
    SiPodman,
    SiHelm,
    SiVault,
    SiSelenium,
    SiCypress,
    SiJest,
    SiVitest,
    SiMocha,
    SiPuppeteer,
    SiStorybook,
    SiNpm,
    SiYarn,
    SiPnpm,
    SiGradle,
    SiApachemaven,
    SiWordpress,
    SiShopify,
    SiStrapi,
    SiContentful,
    SiUnity,
    SiUnrealengine,
    SiBlender,
    SiKaggle,
    SiAnaconda,
    SiSentry,
    SiDatadog,
    SiMinio,
    SiApple,
    SiJsonwebtokens,
    SiSocketdotio,
    SiStripe,
    SiPaypal,
    SiWebassembly,
} from 'react-icons/si';

// Neutral slate for monochrome/dark brand logos so they stay visible in both themes.
const SLATE = '#64748B';

// Normalizes a name so lookups ignore case and punctuation, while keeping the
// symbols that distinguish languages ("C++" -> "cplusplus", "C#" -> "csharp",
// so neither collides with "C" -> "c").
export const normalizeSkill = (name) =>
    name
        .toLowerCase()
        .replace(/\+/g, 'plus')
        .replace(/#/g, 'sharp')
        .replace(/[^a-z0-9]/g, '');

// Maps known technologies to a brand icon + accent color. Keys are normalized
// names; aliases (e.g. "js", "gcp", "ml") let hand-typed names still resolve.
export const SKILL_ICONS = {
    // ---- Languages ----
    python: { Icon: SiPython, color: '#3776AB' },
    php: { Icon: SiPhp, color: '#777BB4' },
    javascript: { Icon: SiJavascript, color: '#E6B800' },
    js: { Icon: SiJavascript, color: '#E6B800' },
    typescript: { Icon: SiTypescript, color: '#3178C6' },
    ts: { Icon: SiTypescript, color: '#3178C6' },
    c: { Icon: SiC, color: '#5C6BC0' },
    cplusplus: { Icon: SiCplusplus, color: '#00599C' },
    csharp: { Icon: SiSharp, color: '#239120' },
    java: { Icon: SiOpenjdk, color: '#ED8B00' },
    go: { Icon: SiGo, color: '#00ADD8' },
    golang: { Icon: SiGo, color: '#00ADD8' },
    rust: { Icon: SiRust, color: '#DEA584' },
    ruby: { Icon: SiRuby, color: '#CC342D' },
    kotlin: { Icon: SiKotlin, color: '#7F52FF' },
    swift: { Icon: SiSwift, color: '#F05138' },
    dart: { Icon: SiDart, color: '#0175C2' },
    scala: { Icon: SiScala, color: '#DC322F' },
    r: { Icon: SiR, color: '#276DC3' },
    perl: { Icon: SiPerl, color: '#39457E' },
    lua: { Icon: SiLua, color: '#2C2D72' },
    haskell: { Icon: SiHaskell, color: '#5D4F85' },
    elixir: { Icon: SiElixir, color: '#6E4A7E' },
    bash: { Icon: SiGnubash, color: '#4EAA25' },
    shell: { Icon: Terminal, color: SLATE },
    shellscripting: { Icon: Terminal, color: SLATE },
    solidity: { Icon: SiSolidity, color: SLATE },
    coffeescript: { Icon: SiCoffeescript, color: SLATE },
    html: { Icon: SiHtml5, color: '#E34F26' },
    html5: { Icon: SiHtml5, color: '#E34F26' },
    css: { Icon: SiCss, color: '#1572B6' },
    css3: { Icon: SiCss, color: '#1572B6' },
    htmlcss: { Icon: SiHtml5, color: '#E34F26' },
    sql: { Icon: Database, color: '#0EA5E9' },

    // ---- Frameworks & Libraries ----
    react: { Icon: SiReact, color: '#61DAFB' },
    reactjs: { Icon: SiReact, color: '#61DAFB' },
    reactnative: { Icon: SiReact, color: '#61DAFB' },
    vue: { Icon: SiVuedotjs, color: '#4FC08D' },
    vuejs: { Icon: SiVuedotjs, color: '#4FC08D' },
    angular: { Icon: SiAngular, color: '#DD0031' },
    next: { Icon: SiNextdotjs, color: SLATE },
    nextjs: { Icon: SiNextdotjs, color: SLATE },
    nuxt: { Icon: SiNuxt, color: '#00DC82' },
    nuxtjs: { Icon: SiNuxt, color: '#00DC82' },
    svelte: { Icon: SiSvelte, color: '#FF3E00' },
    sveltekit: { Icon: SiSvelte, color: '#FF3E00' },
    node: { Icon: SiNodedotjs, color: '#5FA04E' },
    nodejs: { Icon: SiNodedotjs, color: '#5FA04E' },
    express: { Icon: SiExpress, color: SLATE },
    expressjs: { Icon: SiExpress, color: SLATE },
    nestjs: { Icon: SiNestjs, color: '#E0234E' },
    laravel: { Icon: SiLaravel, color: '#FF2D20' },
    inertia: { Icon: SiInertia, color: '#9553E9' },
    laravelinertia: { Icon: SiInertia, color: '#9553E9' },
    django: { Icon: SiDjango, color: '#44B78B' },
    flask: { Icon: SiFlask, color: SLATE },
    fastapi: { Icon: SiFastapi, color: '#009688' },
    spring: { Icon: SiSpring, color: '#6DB33F' },
    springboot: { Icon: SiSpringboot, color: '#6DB33F' },
    rubyonrails: { Icon: SiRubyonrails, color: '#D30001' },
    rails: { Icon: SiRubyonrails, color: '#D30001' },
    symfony: { Icon: SiSymfony, color: SLATE },
    dotnet: { Icon: SiDotnet, color: '#512BD4' },
    net: { Icon: SiDotnet, color: '#512BD4' },
    aspnet: { Icon: SiDotnet, color: '#512BD4' },
    jquery: { Icon: SiJquery, color: '#0769AD' },
    bootstrap: { Icon: SiBootstrap, color: '#7952B3' },
    tailwind: { Icon: SiTailwindcss, color: '#38BDF8' },
    tailwindcss: { Icon: SiTailwindcss, color: '#38BDF8' },
    materialui: { Icon: SiMui, color: '#007FFF' },
    mui: { Icon: SiMui, color: '#007FFF' },
    chakraui: { Icon: SiChakraui, color: '#319795' },
    antdesign: { Icon: SiAntdesign, color: '#0170FE' },
    radixui: { Icon: SiRadixui, color: SLATE },
    shadcnui: { Icon: SiShadcnui, color: SLATE },
    redux: { Icon: SiRedux, color: '#764ABC' },
    vite: { Icon: SiVite, color: '#646CFF' },
    webpack: { Icon: SiWebpack, color: '#2C6EBB' },
    sass: { Icon: SiSass, color: '#CC6699' },
    scss: { Icon: SiSass, color: '#CC6699' },
    graphql: { Icon: SiGraphql, color: '#E10098' },
    apollo: { Icon: SiApollographql, color: SLATE },
    flutter: { Icon: SiFlutter, color: '#02569B' },
    electron: { Icon: SiElectron, color: '#47848F' },
    threejs: { Icon: SiThreedotjs, color: SLATE },
    astro: { Icon: SiAstro, color: '#FF5D01' },
    remix: { Icon: SiRemix, color: SLATE },
    solidjs: { Icon: SiSolid, color: '#2C4F7C' },
    gatsby: { Icon: SiGatsby, color: '#663399' },
    alpinejs: { Icon: SiAlpinedotjs, color: '#8BC0D0' },
    pandas: { Icon: SiPandas, color: '#E70488' },
    numpy: { Icon: SiNumpy, color: '#4D77CF' },
    scipy: { Icon: SiScipy, color: '#8CAAE6' },
    scikitlearn: { Icon: SiScikitlearn, color: '#F7931E' },
    tensorflow: { Icon: SiTensorflow, color: '#FF6F00' },
    pytorch: { Icon: SiPytorch, color: '#EE4C2C' },
    keras: { Icon: SiKeras, color: '#D00000' },
    opencv: { Icon: SiOpencv, color: '#5C3EE8' },
    plotly: { Icon: SiPlotly, color: '#636EFA' },
    matplotlib: { Icon: BarChart3, color: '#3B82F6' },
    seaborn: { Icon: BarChart3, color: '#4C72B0' },
    xgboost: { Icon: BarChart3, color: '#38A3A5' },
    streamlit: { Icon: SiStreamlit, color: '#FF4B4B' },
    jupyter: { Icon: SiJupyter, color: '#F37626' },
    huggingface: { Icon: SiHuggingface, color: '#FFD21E' },
    langchain: { Icon: SiLangchain, color: SLATE },

    // ---- Tools & Platforms ----
    git: { Icon: SiGit, color: '#F05032' },
    github: { Icon: SiGithub, color: SLATE },
    gitgithub: { Icon: SiGithub, color: SLATE },
    gitlab: { Icon: SiGitlab, color: '#FC6D26' },
    bitbucket: { Icon: SiBitbucket, color: '#0052CC' },
    docker: { Icon: SiDocker, color: '#2496ED' },
    kubernetes: { Icon: SiKubernetes, color: '#326CE5' },
    k8s: { Icon: SiKubernetes, color: '#326CE5' },
    mysql: { Icon: SiMysql, color: '#4479A1' },
    postgresql: { Icon: SiPostgresql, color: '#4169E1' },
    postgres: { Icon: SiPostgresql, color: '#4169E1' },
    mongodb: { Icon: SiMongodb, color: '#47A248' },
    mongo: { Icon: SiMongodb, color: '#47A248' },
    redis: { Icon: SiRedis, color: '#DC382D' },
    sqlite: { Icon: SiSqlite, color: '#0F80CC' },
    mariadb: { Icon: SiMariadb, color: SLATE },
    firebase: { Icon: SiFirebase, color: '#FFCA28' },
    supabase: { Icon: SiSupabase, color: '#3ECF8E' },
    aws: { Icon: Cloud, color: '#FF9900' },
    amazonwebservices: { Icon: Cloud, color: '#FF9900' },
    googlecloud: { Icon: SiGooglecloud, color: '#4285F4' },
    gcp: { Icon: SiGooglecloud, color: '#4285F4' },
    azure: { Icon: Cloud, color: '#0078D4' },
    microsoftazure: { Icon: Cloud, color: '#0078D4' },
    vercel: { Icon: SiVercel, color: SLATE },
    netlify: { Icon: SiNetlify, color: '#00C7B7' },
    heroku: { Icon: Cloud, color: '#430098' },
    digitalocean: { Icon: SiDigitalocean, color: '#0080FF' },
    cloudflare: { Icon: SiCloudflare, color: '#F38020' },
    nginx: { Icon: SiNginx, color: '#009639' },
    apache: { Icon: SiApache, color: '#D22128' },
    linux: { Icon: SiLinux, color: SLATE },
    ubuntu: { Icon: SiUbuntu, color: '#E95420' },
    debian: { Icon: SiDebian, color: '#A81D33' },
    redhat: { Icon: SiRedhat, color: '#EE0000' },
    figma: { Icon: SiFigma, color: '#F24E1E' },
    sketch: { Icon: SiSketch, color: '#F7B500' },
    postman: { Icon: SiPostman, color: '#FF6C37' },
    insomnia: { Icon: SiInsomnia, color: '#4000BF' },
    swagger: { Icon: SiSwagger, color: '#85EA2D' },
    jira: { Icon: SiJira, color: '#0052CC' },
    confluence: { Icon: SiConfluence, color: '#2684FF' },
    trello: { Icon: SiTrello, color: '#0052CC' },
    notion: { Icon: SiNotion, color: SLATE },
    asana: { Icon: SiAsana, color: '#F06A6A' },
    clickup: { Icon: SiClickup, color: '#7B68EE' },
    slack: { Icon: MessageSquare, color: '#E01E5A' },
    vscode: { Icon: Code2, color: '#007ACC' },
    visualstudiocode: { Icon: Code2, color: '#007ACC' },
    vim: { Icon: SiVim, color: '#019733' },
    androidstudio: { Icon: SiAndroidstudio, color: '#3DDC84' },
    xcode: { Icon: SiXcode, color: '#147EFB' },
    intellijidea: { Icon: SiIntellijidea, color: SLATE },
    terraform: { Icon: SiTerraform, color: '#7B42BC' },
    ansible: { Icon: SiAnsible, color: SLATE },
    jenkins: { Icon: SiJenkins, color: '#D24939' },
    githubactions: { Icon: SiGithubactions, color: '#2088FF' },
    circleci: { Icon: SiCircleci, color: SLATE },
    prisma: { Icon: SiPrisma, color: SLATE },
    elasticsearch: { Icon: SiElasticsearch, color: '#43A047' },
    kafka: { Icon: SiApachekafka, color: SLATE },
    apachekafka: { Icon: SiApachekafka, color: SLATE },
    rabbitmq: { Icon: SiRabbitmq, color: '#FF6600' },
    grafana: { Icon: SiGrafana, color: '#F46800' },
    prometheus: { Icon: SiPrometheus, color: '#E6522C' },
    podman: { Icon: SiPodman, color: '#892CA0' },
    helm: { Icon: SiHelm, color: '#277A9F' },
    vault: { Icon: SiVault, color: SLATE },
    selenium: { Icon: SiSelenium, color: '#43B02A' },
    cypress: { Icon: SiCypress, color: SLATE },
    jest: { Icon: SiJest, color: '#C21325' },
    vitest: { Icon: SiVitest, color: '#FCC72B' },
    mocha: { Icon: SiMocha, color: '#8D6748' },
    playwright: { Icon: TestTube, color: '#2EAD33' },
    puppeteer: { Icon: SiPuppeteer, color: SLATE },
    storybook: { Icon: SiStorybook, color: '#FF4785' },
    npm: { Icon: SiNpm, color: '#CB3837' },
    yarn: { Icon: SiYarn, color: '#2C8EBB' },
    pnpm: { Icon: SiPnpm, color: '#F69220' },
    gradle: { Icon: SiGradle, color: SLATE },
    maven: { Icon: SiApachemaven, color: '#C71A36' },
    wordpress: { Icon: SiWordpress, color: '#21759B' },
    shopify: { Icon: SiShopify, color: '#7AB55C' },
    strapi: { Icon: SiStrapi, color: '#4945FF' },
    contentful: { Icon: SiContentful, color: '#2478CC' },
    unity: { Icon: SiUnity, color: SLATE },
    unrealengine: { Icon: SiUnrealengine, color: SLATE },
    blender: { Icon: SiBlender, color: '#E87D0D' },
    kaggle: { Icon: SiKaggle, color: '#20BEFF' },
    anaconda: { Icon: SiAnaconda, color: '#44A833' },
    sentry: { Icon: SiSentry, color: SLATE },
    datadog: { Icon: SiDatadog, color: '#632CA6' },
    minio: { Icon: SiMinio, color: '#C72E49' },
    tableau: { Icon: BarChart3, color: '#E97627' },
    powerbi: { Icon: BarChart3, color: '#F2C811' },
    macos: { Icon: SiApple, color: SLATE },
    ios: { Icon: SiApple, color: SLATE },

    // ---- Methodologies ----
    agile: { Icon: RefreshCw, color: '#22C55E' },
    scrum: { Icon: Users, color: '#38BDF8' },
    kanban: { Icon: KanbanSquare, color: '#38BDF8' },
    cicd: { Icon: GitBranch, color: '#60A5FA' },
    devops: { Icon: Workflow, color: '#8B5CF6' },
    unittesting: { Icon: TestTube, color: '#F97316' },
    tdd: { Icon: TestTube, color: '#F97316' },
    testdrivendevelopment: { Icon: TestTube, color: '#F97316' },
    oop: { Icon: Boxes, color: '#60A5FA' },
    objectorientedprogramming: { Icon: Boxes, color: '#60A5FA' },
    mvc: { Icon: Layers, color: '#818CF8' },
    microservices: { Icon: Boxes, color: '#A78BFA' },
    designpatterns: { Icon: Component, color: '#F59E0B' },
    systemdesign: { Icon: Waypoints, color: '#A78BFA' },
    gitflow: { Icon: GitMerge, color: '#F05032' },

    // ---- Other / concepts ----
    rest: { Icon: Server, color: '#F472B6' },
    restapi: { Icon: Server, color: '#F472B6' },
    restapis: { Icon: Server, color: '#F472B6' },
    api: { Icon: Plug, color: '#A78BFA' },
    apis: { Icon: Plug, color: '#A78BFA' },
    apiintegration: { Icon: Plug, color: '#A78BFA' },
    authentication: { Icon: Shield, color: '#34D399' },
    auth: { Icon: Shield, color: '#34D399' },
    authorization: { Icon: Lock, color: '#34D399' },
    jwt: { Icon: SiJsonwebtokens, color: SLATE },
    oauth: { Icon: Lock, color: '#A78BFA' },
    websockets: { Icon: SiSocketdotio, color: SLATE },
    socketio: { Icon: SiSocketdotio, color: SLATE },
    database: { Icon: Database, color: '#22D3EE' },
    databasedesign: { Icon: Database, color: '#22D3EE' },
    payment: { Icon: CreditCard, color: '#10B981' },
    paymentgatewayintegration: { Icon: CreditCard, color: '#10B981' },
    stripe: { Icon: SiStripe, color: '#635BFF' },
    paypal: { Icon: SiPaypal, color: '#00457C' },
    seo: { Icon: Search, color: '#F59E0B' },
    webassembly: { Icon: SiWebassembly, color: '#654FF0' },
    wasm: { Icon: SiWebassembly, color: '#654FF0' },
    webscraping: { Icon: Search, color: '#22D3EE' },
    ai: { Icon: Sparkles, color: '#F59E0B' },
    aitools: { Icon: Sparkles, color: '#F59E0B' },
    promptengineering: { Icon: Sparkles, color: '#F59E0B' },
    machinelearning: { Icon: Brain, color: '#F472B6' },
    ml: { Icon: Brain, color: '#F472B6' },
    deeplearning: { Icon: Brain, color: '#A78BFA' },
    nlp: { Icon: MessageSquare, color: '#34D399' },
    datascience: { Icon: Brain, color: '#6366F1' },
    dataanalysis: { Icon: BarChart3, color: '#22D3EE' },
    datavisualization: { Icon: BarChart3, color: '#38BDF8' },
    cloudcomputing: { Icon: Cloud, color: '#38BDF8' },
    cybersecurity: { Icon: ShieldCheck, color: '#22C55E' },
    webdevelopment: { Icon: Globe, color: '#38BDF8' },
    mobiledevelopment: { Icon: Smartphone, color: '#34D399' },
    responsivedesign: { Icon: Smartphone, color: '#38BDF8' },
    uiuxdesign: { Icon: Palette, color: '#F472B6' },
    datastructures: { Icon: Binary, color: '#38BDF8' },
    algorithms: { Icon: Binary, color: '#818CF8' },
    datastructuresalgorithms: { Icon: Binary, color: '#38BDF8' },
    dsa: { Icon: Binary, color: '#38BDF8' },
    networking: { Icon: Network, color: '#34D399' },
    debugging: { Icon: Bug, color: '#F97316' },
    performanceoptimization: { Icon: Gauge, color: '#22C55E' },
};

// Generic fallback so custom/hand-typed skills that aren't in the map still render.
export const FALLBACK_ICON = { Icon: Code2, color: '#94A3B8' };

export const getSkillIcon = (name) => SKILL_ICONS[normalizeSkill(name)] ?? FALLBACK_ICON;

// True when a name resolves to a real (non-fallback) brand/concept icon.
export const hasSkillIcon = (name) => Boolean(SKILL_ICONS[normalizeSkill(name)]);

// Curated, categorized list of skills the admin can add with one click. Each
// canonical `name` is guaranteed to resolve to an icon via SKILL_ICONS above.
// `category` values match Skill::CATEGORIES on the backend.
export const SKILL_CATALOG = [
    // ---- Languages ----
    { name: 'Python', category: 'Languages' },
    { name: 'JavaScript', category: 'Languages' },
    { name: 'TypeScript', category: 'Languages' },
    { name: 'PHP', category: 'Languages' },
    { name: 'Java', category: 'Languages' },
    { name: 'C', category: 'Languages' },
    { name: 'C++', category: 'Languages' },
    { name: 'C#', category: 'Languages' },
    { name: 'Go', category: 'Languages' },
    { name: 'Rust', category: 'Languages' },
    { name: 'Ruby', category: 'Languages' },
    { name: 'Kotlin', category: 'Languages' },
    { name: 'Swift', category: 'Languages' },
    { name: 'Dart', category: 'Languages' },
    { name: 'Scala', category: 'Languages' },
    { name: 'R', category: 'Languages' },
    { name: 'Perl', category: 'Languages' },
    { name: 'Lua', category: 'Languages' },
    { name: 'Haskell', category: 'Languages' },
    { name: 'Elixir', category: 'Languages' },
    { name: 'Solidity', category: 'Languages' },
    { name: 'Bash', category: 'Languages' },
    { name: 'SQL', category: 'Languages' },
    { name: 'HTML', category: 'Languages' },
    { name: 'CSS', category: 'Languages' },
    { name: 'HTML/CSS', category: 'Languages' },

    // ---- Frameworks & Libraries ----
    { name: 'React', category: 'Frameworks & Libraries' },
    { name: 'Vue.js', category: 'Frameworks & Libraries' },
    { name: 'Angular', category: 'Frameworks & Libraries' },
    { name: 'Next.js', category: 'Frameworks & Libraries' },
    { name: 'Nuxt', category: 'Frameworks & Libraries' },
    { name: 'Svelte', category: 'Frameworks & Libraries' },
    { name: 'Astro', category: 'Frameworks & Libraries' },
    { name: 'Remix', category: 'Frameworks & Libraries' },
    { name: 'Gatsby', category: 'Frameworks & Libraries' },
    { name: 'React Native', category: 'Frameworks & Libraries' },
    { name: 'Flutter', category: 'Frameworks & Libraries' },
    { name: 'Electron', category: 'Frameworks & Libraries' },
    { name: 'Node.js', category: 'Frameworks & Libraries' },
    { name: 'Express', category: 'Frameworks & Libraries' },
    { name: 'NestJS', category: 'Frameworks & Libraries' },
    { name: 'Laravel', category: 'Frameworks & Libraries' },
    { name: 'Laravel Inertia', category: 'Frameworks & Libraries' },
    { name: 'Django', category: 'Frameworks & Libraries' },
    { name: 'Flask', category: 'Frameworks & Libraries' },
    { name: 'FastAPI', category: 'Frameworks & Libraries' },
    { name: 'Spring Boot', category: 'Frameworks & Libraries' },
    { name: 'Ruby on Rails', category: 'Frameworks & Libraries' },
    { name: 'Symfony', category: 'Frameworks & Libraries' },
    { name: '.NET', category: 'Frameworks & Libraries' },
    { name: 'jQuery', category: 'Frameworks & Libraries' },
    { name: 'Bootstrap', category: 'Frameworks & Libraries' },
    { name: 'Tailwind CSS', category: 'Frameworks & Libraries' },
    { name: 'Material UI', category: 'Frameworks & Libraries' },
    { name: 'Chakra UI', category: 'Frameworks & Libraries' },
    { name: 'Ant Design', category: 'Frameworks & Libraries' },
    { name: 'shadcn/ui', category: 'Frameworks & Libraries' },
    { name: 'Redux', category: 'Frameworks & Libraries' },
    { name: 'Sass', category: 'Frameworks & Libraries' },
    { name: 'GraphQL', category: 'Frameworks & Libraries' },
    { name: 'Apollo', category: 'Frameworks & Libraries' },
    { name: 'Three.js', category: 'Frameworks & Libraries' },
    { name: 'Vite', category: 'Frameworks & Libraries' },
    { name: 'Webpack', category: 'Frameworks & Libraries' },
    { name: 'Pandas', category: 'Frameworks & Libraries' },
    { name: 'NumPy', category: 'Frameworks & Libraries' },
    { name: 'SciPy', category: 'Frameworks & Libraries' },
    { name: 'Scikit-learn', category: 'Frameworks & Libraries' },
    { name: 'TensorFlow', category: 'Frameworks & Libraries' },
    { name: 'PyTorch', category: 'Frameworks & Libraries' },
    { name: 'Keras', category: 'Frameworks & Libraries' },
    { name: 'OpenCV', category: 'Frameworks & Libraries' },
    { name: 'Matplotlib', category: 'Frameworks & Libraries' },
    { name: 'Seaborn', category: 'Frameworks & Libraries' },
    { name: 'Plotly', category: 'Frameworks & Libraries' },
    { name: 'XGBoost', category: 'Frameworks & Libraries' },
    { name: 'Streamlit', category: 'Frameworks & Libraries' },
    { name: 'Jupyter', category: 'Frameworks & Libraries' },
    { name: 'Hugging Face', category: 'Frameworks & Libraries' },
    { name: 'LangChain', category: 'Frameworks & Libraries' },

    // ---- Tools & Platforms ----
    { name: 'Git', category: 'Tools & Platforms' },
    { name: 'GitHub', category: 'Tools & Platforms' },
    { name: 'GitLab', category: 'Tools & Platforms' },
    { name: 'Bitbucket', category: 'Tools & Platforms' },
    { name: 'Docker', category: 'Tools & Platforms' },
    { name: 'Kubernetes', category: 'Tools & Platforms' },
    { name: 'MySQL', category: 'Tools & Platforms' },
    { name: 'PostgreSQL', category: 'Tools & Platforms' },
    { name: 'MongoDB', category: 'Tools & Platforms' },
    { name: 'Redis', category: 'Tools & Platforms' },
    { name: 'SQLite', category: 'Tools & Platforms' },
    { name: 'MariaDB', category: 'Tools & Platforms' },
    { name: 'Elasticsearch', category: 'Tools & Platforms' },
    { name: 'Prisma', category: 'Tools & Platforms' },
    { name: 'Firebase', category: 'Tools & Platforms' },
    { name: 'Supabase', category: 'Tools & Platforms' },
    { name: 'AWS', category: 'Tools & Platforms' },
    { name: 'Google Cloud', category: 'Tools & Platforms' },
    { name: 'Azure', category: 'Tools & Platforms' },
    { name: 'Vercel', category: 'Tools & Platforms' },
    { name: 'Netlify', category: 'Tools & Platforms' },
    { name: 'Heroku', category: 'Tools & Platforms' },
    { name: 'DigitalOcean', category: 'Tools & Platforms' },
    { name: 'Cloudflare', category: 'Tools & Platforms' },
    { name: 'Nginx', category: 'Tools & Platforms' },
    { name: 'Apache', category: 'Tools & Platforms' },
    { name: 'Linux', category: 'Tools & Platforms' },
    { name: 'Ubuntu', category: 'Tools & Platforms' },
    { name: 'Terraform', category: 'Tools & Platforms' },
    { name: 'Ansible', category: 'Tools & Platforms' },
    { name: 'Jenkins', category: 'Tools & Platforms' },
    { name: 'GitHub Actions', category: 'Tools & Platforms' },
    { name: 'CircleCI', category: 'Tools & Platforms' },
    { name: 'Kafka', category: 'Tools & Platforms' },
    { name: 'RabbitMQ', category: 'Tools & Platforms' },
    { name: 'Grafana', category: 'Tools & Platforms' },
    { name: 'Prometheus', category: 'Tools & Platforms' },
    { name: 'Figma', category: 'Tools & Platforms' },
    { name: 'Sketch', category: 'Tools & Platforms' },
    { name: 'Postman', category: 'Tools & Platforms' },
    { name: 'Insomnia', category: 'Tools & Platforms' },
    { name: 'Swagger', category: 'Tools & Platforms' },
    { name: 'Jira', category: 'Tools & Platforms' },
    { name: 'Confluence', category: 'Tools & Platforms' },
    { name: 'Trello', category: 'Tools & Platforms' },
    { name: 'Notion', category: 'Tools & Platforms' },
    { name: 'Slack', category: 'Tools & Platforms' },
    { name: 'VS Code', category: 'Tools & Platforms' },
    { name: 'Selenium', category: 'Tools & Platforms' },
    { name: 'Cypress', category: 'Tools & Platforms' },
    { name: 'Jest', category: 'Tools & Platforms' },
    { name: 'Playwright', category: 'Tools & Platforms' },
    { name: 'Storybook', category: 'Tools & Platforms' },
    { name: 'npm', category: 'Tools & Platforms' },
    { name: 'Yarn', category: 'Tools & Platforms' },
    { name: 'WordPress', category: 'Tools & Platforms' },
    { name: 'Shopify', category: 'Tools & Platforms' },
    { name: 'Strapi', category: 'Tools & Platforms' },
    { name: 'Unity', category: 'Tools & Platforms' },
    { name: 'Blender', category: 'Tools & Platforms' },
    { name: 'Kaggle', category: 'Tools & Platforms' },
    { name: 'Power BI', category: 'Tools & Platforms' },
    { name: 'Tableau', category: 'Tools & Platforms' },

    // ---- Methodologies ----
    { name: 'Agile', category: 'Methodologies' },
    { name: 'Scrum', category: 'Methodologies' },
    { name: 'Kanban', category: 'Methodologies' },
    { name: 'CI/CD', category: 'Methodologies' },
    { name: 'DevOps', category: 'Methodologies' },
    { name: 'Unit Testing', category: 'Methodologies' },
    { name: 'TDD', category: 'Methodologies' },
    { name: 'OOP', category: 'Methodologies' },
    { name: 'MVC', category: 'Methodologies' },
    { name: 'Microservices', category: 'Methodologies' },
    { name: 'Design Patterns', category: 'Methodologies' },
    { name: 'System Design', category: 'Methodologies' },

    // ---- Other ----
    { name: 'REST APIs', category: 'Other' },
    { name: 'API Integration', category: 'Other' },
    { name: 'GraphQL', category: 'Other' },
    { name: 'Authentication', category: 'Other' },
    { name: 'JWT', category: 'Other' },
    { name: 'OAuth', category: 'Other' },
    { name: 'WebSockets', category: 'Other' },
    { name: 'Database Design', category: 'Other' },
    { name: 'Payment Gateway Integration', category: 'Other' },
    { name: 'Stripe', category: 'Other' },
    { name: 'Machine Learning', category: 'Other' },
    { name: 'Deep Learning', category: 'Other' },
    { name: 'NLP', category: 'Other' },
    { name: 'Data Science', category: 'Other' },
    { name: 'Data Analysis', category: 'Other' },
    { name: 'Cloud Computing', category: 'Other' },
    { name: 'Cybersecurity', category: 'Other' },
    { name: 'Web Development', category: 'Other' },
    { name: 'Mobile Development', category: 'Other' },
    { name: 'UI/UX Design', category: 'Other' },
    { name: 'Responsive Design', category: 'Other' },
    { name: 'Data Structures & Algorithms', category: 'Other' },
    { name: 'Networking', category: 'Other' },
    { name: 'SEO', category: 'Other' },
    { name: 'AI Tools', category: 'Other' },
    { name: 'Prompt Engineering', category: 'Other' },
];

// Small reusable colored icon badge. `size` controls the square dimensions.
export function SkillGlyph({ name, className = '', size = 'h-9 w-9', iconSize = 'h-5 w-5' }) {
    const { Icon, color } = getSkillIcon(name);
    return (
        <span
            className={`flex items-center justify-center rounded-lg ${size} ${className}`}
            style={{ color, backgroundColor: `${color}22` }}
        >
            <Icon className={iconSize} />
        </span>
    );
}
